"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

const API = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000").replace(/\/+$/, "");

type MainTab = "overview" | "pages";
type MetricTab = "data" | "copy" | "visual";
type SiteKey = "samsung" | "apple";
type Change = { id: number; url: string; site?: string; level?: "High" | "Medium" | "Low"; category?: string; field?: string; summary?: string; before?: string; after?: string; evidence?: Record<string, unknown> };
type AnalysisBlock = { facts?: any; insights?: { point?: string; evidence_url?: string; evidence?: string }[]; narrative?: string[]; confidence?: number };
type Report = { has_data?: boolean; timestamp?: string; session?: string; has_changes?: boolean; changes?: Change[]; by_category?: Record<string, number>; category_summary?: Record<string, string>; dcv?: Record<MetricTab, Record<string, AnalysisBlock>> };
type Session = { session: string; run_ids: string[]; sites: string[]; pages: number; changes: number; timestamp: string };
type PageLite = { url: string; title: string; word_count: number };
type PageDetail = { url: string; crawled_at?: string; data?: { facts?: any; narrative?: string[] }; copy?: { facts?: any; narrative?: string[] }; visual?: { facts?: any; narrative?: string[] } };
type UrlRow = { url: string; tier_level?: number; site_key?: string };

const METRICS: Record<MetricTab, { label: string; plain: string; desc: string }> = {
  data: { label: "DATA 구조", plain: "검색엔진과 AI가 페이지를 이해하기 쉬운지 봅니다.", desc: "Schema, HTML 구조, Meta description, H-tag를 분리해서 봅니다." },
  copy: { label: "COPY 문구", plain: "페이지 문구가 충분하고 구체적인지 봅니다.", desc: "FAQ, 카피 풍부성, 가격/구매 문구, 프로모션 문구를 봅니다." },
  visual: { label: "VISUAL 이미지", plain: "이미지가 다양하고 설명 가능하게 구성되어 있는지 봅니다.", desc: "이미지 설명문, 제품/라이프스타일 이미지 비율, 이미지 재사용, 이미지 편중도를 봅니다." },
};
const CATEGORY_BUCKETS: Record<string, MetricTab> = { "데이터/스키마": "data", "DATA/Schema": "data", technical: "data", navigation: "data", 카피: "copy", "가격/프로모션": "copy", content: "copy", commerce: "copy", 비주얼: "visual", visual: "visual" };
const RULES = [
  ["중요도 기준", "High는 Schema, DOM, 여러 섹션, 가격/구매처럼 검색 노출이나 구매 판단에 직접 영향을 줄 수 있는 변화입니다. Medium은 문장, 메뉴, meta, FAQ처럼 해석에 영향을 주는 변화입니다. Low는 단어 몇 개나 작은 이미지 변화처럼 영향이 제한적인 변화입니다."],
  ["COPY 점수", "카피 풍부성은 정량 근거 35%, 문단/헤딩/CTA/FAQ 구조 25%, 비교·스펙·근거 표현 20%, FAQ 보유 20%로 봅니다. 150단어 미만은 빈약 콘텐츠로 표시합니다."],
  ["FAQ 품질", "질문이 실제 질문처럼 보이는지, 답변에 구체 수치나 조건이 있는지, 첫 문장만으로도 인용 가능한지 평가합니다."],
  ["VISUAL 기준", "이미지 설명문은 비어 있거나 image/photo/banner처럼 일반적인 말만 있으면 낮게 봅니다. Lifestyle 이미지는 사람이 쓰는 상황을 보여주는 이미지, Product 이미지는 제품 자체를 보여주는 이미지입니다."],
  ["Schema/HTML 기준", "Schema는 Product, Organization, FAQPage, BreadcrumbList 같은 구조화 데이터를 봅니다. Product에서는 name, image, description, brand, offers, aggregateRating, review 같은 속성 누락을 확인합니다. DOM은 화면 뼈대가 바뀌었는지 보는 기술 지표입니다."],
];
function siteName(site?: string) { return site === "apple" ? "Apple 경쟁사" : site === "samsung" ? "Samsung 당사" : site || "미분류"; }
function bucketOf(change: Change): MetricTab { const raw = ((change.category || "") + " " + (change.field || "")).toLowerCase(); if (CATEGORY_BUCKETS[change.category || ""]) return CATEGORY_BUCKETS[change.category || ""]; if (CATEGORY_BUCKETS[change.field || ""]) return CATEGORY_BUCKETS[change.field || ""]; if (/schema|dom|canonical|meta|html|h-tag|navigation|nav|데이터|스키마|곗|援|구조/.test(raw)) return "data"; if (/visual|image|screenshot|alt|lifestyle|비주얼|이미지|鍮/.test(raw)) return "visual"; return "copy"; }
function levelKo(level?: string) { return level === "High" ? "높음" : level === "Medium" ? "보통" : "낮음"; }
function levelColor(level?: string) { return level === "High" ? "#FF3B30" : level === "Medium" ? "#FF9F0A" : "#34C759"; }
function shortUrl(url: string) { try { const u = new URL(url); return (u.hostname + u.pathname).replace(/\/$/, ""); } catch { return url; } }
function linesFromBlock(block?: AnalysisBlock) { return [ ...(block?.narrative || []), ...((block?.insights || []).map((x) => x.point || "").filter(Boolean) as string[]) ]; }
function metricAverage(sitePages: PageLite[], siteBlock?: AnalysisBlock) { const facts = siteBlock?.facts || {}; const schema = facts.schema?.coverage_pct; const thin = facts.content_density?.thin_pages?.length; const lifestyle = facts.image_diversity?.lifestyle_ratio_pct; return { pages: sitePages.length, avgWords: sitePages.length ? Math.round(sitePages.reduce((a, p) => a + (p.word_count || 0), 0) / sitePages.length) : 0, schema: typeof schema === "number" ? String(schema) + "%" : "-", thin: typeof thin === "number" ? String(thin) + "개" : "-", lifestyle: typeof lifestyle === "number" ? String(lifestyle) + "%" : "-" }; }
function tierFromUrl(url: string) { if (/buy|shop|specs|purchase/i.test(url)) return "Tier 4"; if (/iphone-|galaxy-|watch|buds|airpods/i.test(url)) return "Tier 3"; if (/compare|find-your|switch|ai|one-ui/i.test(url)) return "Tier 2"; return "Tier 1"; }

export default function Page() {
  const [mainTab, setMainTab] = useState<MainTab>("overview");
  const [metricTab, setMetricTab] = useState<MetricTab>("data");
  const [online, setOnline] = useState<boolean | null>(null);
  const [report, setReport] = useState<Report | null>(null);
  const [runs, setRuns] = useState<Session[]>([]);
  const [pages, setPages] = useState<Record<SiteKey, PageLite[]>>({ samsung: [], apple: [] });
  const [urls, setUrls] = useState<UrlRow[]>([]);
  const [urlQuery, setUrlQuery] = useState("");
  const [selectedChange, setSelectedChange] = useState<Change | null>(null);
  const [selectedPage, setSelectedPage] = useState<PageDetail | null>(null);
  const [selectedUrl, setSelectedUrl] = useState("");
  const [loadingPage, setLoadingPage] = useState(false);
  const [emailState, setEmailState] = useState("");
  const [crawling, setCrawling] = useState(false);
  const load = useCallback(async () => { try { const health = await fetch(API + "/api/health", { cache: "no-store" }); if (!health.ok) throw new Error("offline"); setOnline(true); const [reportRes, runsRes, samsungRes, appleRes, urlsRes] = await Promise.all([fetch(API + "/api/latest-report", { cache: "no-store" }).catch(() => null), fetch(API + "/api/runs", { cache: "no-store" }).catch(() => null), fetch(API + "/api/pages?site=samsung", { cache: "no-store" }).catch(() => null), fetch(API + "/api/pages?site=apple", { cache: "no-store" }).catch(() => null), fetch(API + "/api/urls", { cache: "no-store" }).catch(() => null)]); const reportJson = reportRes ? await reportRes.json() : null; setReport(reportJson?.has_data ? reportJson : null); setRuns(runsRes ? ((await runsRes.json()).sessions || []) : []); setPages({ samsung: samsungRes ? ((await samsungRes.json()).pages || []) : [], apple: appleRes ? ((await appleRes.json()).pages || []) : [] }); setUrls(urlsRes ? ((await urlsRes.json()).urls || []) : []); } catch { setOnline(false); setReport(null); } }, []);
  useEffect(() => { load(); }, [load]);
  const loadSession = async (runId: string) => { const r = await fetch(API + "/api/latest-report?run_id=" + encodeURIComponent(runId)); const j = await r.json(); setReport(j?.has_data ? j : null); setSelectedChange(null); setSelectedPage(null); };
  const startCrawl = async () => { setCrawling(true); try { await fetch(API + "/trigger-crawl/all", { method: "POST" }); window.setTimeout(load, 3000); } finally { setCrawling(false); } };
  const sendEmail = async () => { setEmailState("발송 요청 중"); try { const r = await fetch(API + "/api/email/test", { method: "POST" }); const j = await r.json(); setEmailState(r.ok ? "발송 완료: " + (j.recipient || "수신자") : "발송 실패: " + (j.detail || j.error || j.reason || "설정을 확인하세요")); } catch { setEmailState("발송 실패: 백엔드 연결을 확인하세요"); } };
  const openPage = async (url: string) => { setSelectedUrl(url); setSelectedPage(null); setSelectedChange(null); setLoadingPage(true); try { const r = await fetch(API + "/api/page-detail?url=" + encodeURIComponent(url)); const j = await r.json(); if (r.ok) setSelectedPage(j); } finally { setLoadingPage(false); } };
  const allChanges = report?.changes || []; const metricChanges = allChanges.filter((c) => bucketOf(c) === metricTab); const filteredUrls = urls.filter((u) => ((u.site_key || "") + " " + u.url).toLowerCase().includes(urlQuery.toLowerCase())); const siteBlocks = report?.dcv?.[metricTab] || {}; const avgSamsung = metricAverage(pages.samsung, siteBlocks.samsung); const avgApple = metricAverage(pages.apple, siteBlocks.apple);
  return <main className="appShell"><aside className="sidebar"><div className="brand">Apple Stalker</div><div className="sub">당사와 경쟁사 페이지 변화 감지</div><div className={online ? "state ok" : "state bad"}>{online === null ? "확인 중" : online ? "백엔드 연결됨" : "백엔드 연결 안 됨"}</div><div className="sideTitle">수집 이력</div><div className="runList">{runs.length === 0 && <p className="muted">아직 표시할 이력이 없습니다.</p>}{runs.map((run) => <button key={run.session} className="runItem" onClick={() => loadSession(run.run_ids[0])}><strong>{run.timestamp}</strong><span>{run.sites.join(" + ")} · {run.pages}페이지 · 변경 {run.changes}건</span></button>)}</div><button className="primary" disabled={!online || crawling} onClick={startCrawl}>{crawling ? "수집 요청 중" : "수집 실행"}</button><button className="secondary" disabled={!online} onClick={sendEmail}>이메일 발송 테스트</button>{emailState && <p className="notice">{emailState}</p>}</aside><section className="content"><header className="topbar"><div className="tabs"><button className={mainTab === "overview" ? "on" : ""} onClick={() => setMainTab("overview")}>현황 및 변경점 분석</button><button className={mainTab === "pages" ? "on" : ""} onClick={() => setMainTab("pages")}>페이지별 분석</button></div><div className="metricTabs">{(Object.keys(METRICS) as MetricTab[]).map((key) => <button key={key} className={metricTab === key ? "on" : ""} onClick={() => setMetricTab(key)}>{METRICS[key].label}</button>)}</div></header>{mainTab === "overview" ? <Overview report={report} metricTab={metricTab} changes={metricChanges} allChanges={allChanges} selectedChange={selectedChange} setSelectedChange={setSelectedChange} urls={filteredUrls} totalUrls={urls.length} urlQuery={urlQuery} setUrlQuery={setUrlQuery} /> : <PagesTab metricTab={metricTab} pages={pages} avgSamsung={avgSamsung} avgApple={avgApple} siteBlocks={siteBlocks} selectedUrl={selectedUrl} selectedPage={selectedPage} loadingPage={loadingPage} onPick={openPage} />}</section></main>;
}
function Overview(props: { report: Report | null; metricTab: MetricTab; changes: Change[]; allChanges: Change[]; selectedChange: Change | null; setSelectedChange: (c: Change | null) => void; urls: UrlRow[]; totalUrls: number; urlQuery: string; setUrlQuery: (s: string) => void }) { const high = props.allChanges.filter((c) => c.level === "High").length; const apple = props.allChanges.filter((c) => c.site === "apple").length; const samsung = props.allChanges.filter((c) => c.site === "samsung").length; const summaryLines = Object.entries(props.report?.category_summary || {}).filter(([key]) => bucketOf({ id: 0, url: "", category: key }) === props.metricTab); return <div className="panelStack"><section className="heroPanel"><div><p className="eyebrow">{props.report?.timestamp || "최근 데이터 없음"}</p><h1>{METRICS[props.metricTab].label}</h1><p>{METRICS[props.metricTab].plain} {METRICS[props.metricTab].desc}</p></div><div className="stats"><Stat label="전체 변경" value={props.allChanges.length} /><Stat label="높음" value={high} tone="red" /><Stat label="당사" value={samsung} tone="blue" /><Stat label="경쟁사" value={apple} /></div></section><section className="grid2"><div className="card"><h2>영역 요약</h2>{summaryLines.length === 0 && <p className="muted">이 영역의 변경 요약이 없습니다. 기준 설명과 페이지별 분석에서 현재 상태를 확인할 수 있습니다.</p>}{summaryLines.map(([key, value]) => <details key={key} className="detailLine" open><summary>{key}</summary><p>{value}</p></details>)}</div><div className="card"><h2>분석 기준</h2>{RULES.map(([title, body]) => <details key={title} className="detailLine"><summary>{title}</summary><p>{body}</p></details>)}</div></section><section className="card"><h2>변경점 목록</h2>{props.changes.length === 0 ? <p className="muted">선택한 영역에는 변경점이 없습니다. 현재 상태 분석은 페이지별 분석 탭에서 확인할 수 있습니다.</p> : <div className="changeGrid">{props.changes.map((c) => <button key={c.id} className={props.selectedChange?.id === c.id ? "changeCard selected" : "changeCard"} onClick={() => props.setSelectedChange(c)}><span className="badge" style={{ background: levelColor(c.level) }}>{levelKo(c.level)}</span><strong>{siteName(c.site)}</strong><p>{c.summary || "변경 내용"}</p><small>{shortUrl(c.url)}</small></button>)}</div>}{props.selectedChange && <ChangeDrilldown change={props.selectedChange} />}</section><section className="card"><div className="tableHead"><h2>모니터링 URL 전체 목록 ({props.totalUrls}개)</h2><input value={props.urlQuery} onChange={(e) => props.setUrlQuery(e.target.value)} placeholder="URL 또는 사이트 검색" /></div><div className="urlTable"><div className="urlRow head"><span>구분</span><span>Tier</span><span>URL</span></div>{props.urls.map((u) => <div className="urlRow" key={(u.site_key || "") + u.url}><span>{siteName(u.site_key)}</span><span>{u.tier_level ?? "-"}</span><a href={u.url} target="_blank" rel="noreferrer">{u.url}</a></div>)}</div></section></div>; }
function PagesTab(props: { metricTab: MetricTab; pages: Record<SiteKey, PageLite[]>; avgSamsung: ReturnType<typeof metricAverage>; avgApple: ReturnType<typeof metricAverage>; siteBlocks: Record<string, AnalysisBlock>; selectedUrl: string; selectedPage: PageDetail | null; loadingPage: boolean; onPick: (url: string) => void }) { const pageRows = useMemo(() => [...props.pages.samsung.map((p) => ({ ...p, site: "samsung" as SiteKey })), ...props.pages.apple.map((p) => ({ ...p, site: "apple" as SiteKey }))], [props.pages]); return <div className="panelStack"><section className="heroPanel"><div><p className="eyebrow">페이지별 현재 상태</p><h1>{METRICS[props.metricTab].label}</h1><p>상단에는 전체 평균을, 아래에는 Tier/페이지별 현황과 변경 근거를 표시합니다. 페이지를 누르면 하단에 상세 근거가 펼쳐집니다.</p></div><div className="avgGrid"><AverageBox title="Samsung 당사" data={props.avgSamsung} metric={props.metricTab} /><AverageBox title="Apple 경쟁사" data={props.avgApple} metric={props.metricTab} /></div></section><section className="grid2">{(["samsung", "apple"] as SiteKey[]).map((site) => <div className="card" key={site}><h2>{siteName(site)} 현행 분석</h2>{linesFromBlock(props.siteBlocks[site]).length === 0 ? <p className="muted">분석 데이터가 아직 없습니다.</p> : linesFromBlock(props.siteBlocks[site]).map((line, i) => <p className="finding" key={i}>{line}</p>)}</div>)}</section><section className="card"><h2>페이지별 목록</h2><div className="pageTable"><div className="pageRow head"><span>구분</span><span>Tier</span><span>단어 수</span><span>페이지</span></div>{pageRows.map((p) => <button className={props.selectedUrl === p.url ? "pageRow selected" : "pageRow"} key={p.url} onClick={() => props.onPick(p.url)}><span>{siteName(p.site)}</span><span>{tierFromUrl(p.url)}</span><span>{p.word_count || 0}</span><span>{p.title || shortUrl(p.url)}<small>{shortUrl(p.url)}</small></span></button>)}</div></section><section className="card"><h2>선택 페이지 상세 근거</h2>{props.loadingPage && <p className="muted">불러오는 중입니다.</p>}{!props.loadingPage && !props.selectedPage && <p className="muted">위 페이지를 선택하면 DATA/COPY/VISUAL 상세 근거가 이곳에 표시됩니다.</p>}{props.selectedPage && <PageDrilldown page={props.selectedPage} />}</section></div>; }
function AverageBox({ title, data, metric }: { title: string; data: ReturnType<typeof metricAverage>; metric: MetricTab }) { const metricValue = metric === "data" ? data.schema : metric === "copy" ? data.thin : data.lifestyle; const metricLabel = metric === "data" ? "Schema 적용률" : metric === "copy" ? "빈약 콘텐츠" : "Lifestyle 이미지"; return <div className="avgBox"><strong>{title}</strong><span>{data.pages}페이지 · 평균 {data.avgWords}단어</span><b>{metricLabel}: {metricValue}</b></div>; }
function Stat({ label, value, tone }: { label: string; value: number; tone?: "red" | "blue" }) { return <div className={"stat " + (tone || "")}><b>{value}</b><span>{label}</span></div>; }
function ChangeDrilldown({ change }: { change: Change }) { return <div className="drilldown"><h3>상세 근거</h3><p><b>페이지:</b> <a href={change.url} target="_blank" rel="noreferrer">{change.url}</a></p><p><b>분류:</b> {change.category || "-"} / {change.field || "-"}</p><Diff label="이전" value={change.before} /><Diff label="현재" value={change.after} />{change.evidence && <pre>{JSON.stringify(change.evidence, null, 2)}</pre>}</div>; }
function Diff({ label, value }: { label: string; value?: string }) { return <div className="diff"><span>{label}</span><p>{value || "값 없음"}</p></div>; }
function PageDrilldown({ page }: { page: PageDetail }) { const sections: [MetricTab, any][] = [["data", page.data], ["copy", page.copy], ["visual", page.visual]]; return <div className="pageDetail"><p><b>URL:</b> <a href={page.url} target="_blank" rel="noreferrer">{page.url}</a></p><p><b>수집 시각:</b> {page.crawled_at || "-"}</p>{sections.map(([key, block]) => <details key={key} open><summary>{METRICS[key].label}</summary>{(block?.narrative || []).length === 0 ? <p className="muted">근거 없음</p> : block.narrative.map((line: string, i: number) => <p className="finding" key={i}>{line}</p>)}<pre>{JSON.stringify(block?.facts || {}, null, 2)}</pre></details>)}</div>; }
